### ISSUE TITLE
Error in Android Studio 'Default activity not found'

### ISSUE THREAD

**Issue by MayukhaC** [wso2/product-emm#373]
I am trying to install the wso2emm as an android system service so that i can silent install apps as per instructions [here](https://docs.wso2.com/display/EMM210/Integrating+the+Android+System+Service+Application)

I have imported the android.jar which has permissions for restricted api. But the red cross mark on the android symbol wont go and error sayiing "DEFAULT ACTIVITY NOT FOUND" appears.Has it anything to do with signing the application with device firmware?

**Comment by MayukhaC** [comment]
In the source code of 'system service app', the manifest file does not contain .MAIN and .LAUNCHER in the intent filter. I tried adding the mentioned intent-filters to the .Mainactivity and the error vanished. But is that the right way? I wonderwhy it is not done in the source code.

**Comment by kasundananjaya** [comment]
Hi,

MAIN/LAUNCHER is taken off from the system service app because it should not appear on user's app list as an app and it should just be a background service working as a system level privileged application. So regardless of above warning, you can build and push the APK to the device using ADB console. 

In addition, please note that the system service requires root privileges or the system service needs to be signed by the OS signing certificate. Refer http://wso2.com/library/articles/2016/07/article-advanced-handling-of-cope-android-devices-using-wso2-enterprise-mobility-manager/ for more info on this.

**Comment by MayukhaC** [comment]
@kasundananjaya Oh. Its great to know that. Thank you for pointing this . I never thought of it like that.
